In [1]:
import numpy as np
np.random.seed(seed=60)
random_square = np.random.rand(5,5)
random_square

array([[0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ],
       [0.39825396, 0.37941492, 0.01058154, 0.1703656 , 0.12339337],
       [0.69240128, 0.87444156, 0.3373969 , 0.99245923, 0.13154007],
       [0.50032984, 0.28662051, 0.22058485, 0.50208555, 0.63606254],
       [0.63567694, 0.08043309, 0.58143375, 0.83919086, 0.29301825]])

In [2]:
# First row
random_square[0]

array([0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ])

In [3]:
# First row
random_square[0,:]

array([0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ])

In [4]:
# First column
random_square[:,0]

array([0.30087333, 0.39825396, 0.69240128, 0.50032984, 0.63567694])

In [5]:
# First entry
random_square[0,0]

0.30087333004661876

In [6]:
# First entry using another way
random_square[0][0]

0.30087333004661876

In [7]:
random_square[2,3]

0.9924592256795676

In [8]:
# Mean entry of matrix
random_square.mean()

0.42917627159618377

In [9]:
# Mean entry of first row
random_square[0].mean()

0.4087444389228477

In [10]:
# Mean entry of last column
random_square[:,-1].mean()

0.35019700684996913