In [1]:
import threading
import queue
import cProfile
import itertools
import numpy as np

In [2]:
in_queue = queue.Queue()
out_queue = queue.Queue()

In [3]:
def random_number_threading():
    while True:
        n = in_queue.get()
        if n == 'STOP':
            return
        random_numbers = np.random.rand(n)
        out_queue.put(random_numbers)

In [4]:
def generate_random_numbers(show_output, up_to):
    thread = threading.Thread(target=random_number_threading)
    thread.start()
    for i in range(up_to):
        in_queue.put(i)
        random_nums = out_queue.get()
        if show_output:
            print(random_nums)
    in_queue.put('STOP')
    thread.join()

In [5]:
generate_random_numbers(True, 10)

[]
[0.78155881]
[0.61671875 0.96379795]
[0.52748128 0.69182391 0.11764897]
[0.89243527 0.75566451 0.88089298 0.15782374]
[0.1140009  0.25980504 0.88632411 0.08730527 0.17493792]
[0.41370041 0.01167654 0.60758276 0.73804504 0.73648781 0.29094613]
[0.8317736  0.57914287 0.01291246 0.61011878 0.91729392 0.50898183
 0.24640681]
[0.4475645  0.94036652 0.69823962 0.37459892 0.15512432 0.15115215
 0.65882522 0.77908825]
[0.42420881 0.7135031  0.22843178 0.20624473 0.32533328 0.86108686
 0.46407033 0.81794371 0.98958707]


In [6]:
cProfile.run('generate_random_numbers(False, 20000)')

         740056 function calls in 3.461 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.051    0.051    3.461    3.461 <ipython-input-4-04f1b90debed>:1(generate_random_numbers)
        1    0.000    0.000    3.461    3.461 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:38(_remove)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:81(add)
    20001    0.063    0.000    0.200    0.000 queue.py:121(put)
    20000    0.137    0.000    3.209    0.000 queue.py:153(get)
    40000    0.019    0.000    0.026    0.000 queue.py:208(_qsize)
    20001    0.009    0.000    0.012    0.000 queue.py:212(_put)
    20000    0.008    0.000    0.012    0.000 queue.py:216(_get)
        1    0.000    0.000    0.000    0.000 threading.py:1000(join)
        1    0.000    0.000    0.000    0.000 threading.py:1038(_wait_for_tstate_lock)
        1    0.000    0.000    0.000    0.000 threadin